version: '3.9'
services:
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      mysql_root_password:root
    ports:
      -3306:3306
  adminer:
    image: adminer
    platform: linux/arm64/v8
    restart: always
    ports:
      -8080:8080
